fps: 20
buildings:
    woodcutter:
        ins: []
        outs:
            - wood
        speed:
            48
    warehouse:
        ins: []
        outs: []
        speed: 0
items:
    types:
        wood:

