fps: 20
buildings:
    woodcutter:
        ins: []
        outs:
            - wood
        speed:
            48
        materials: []
    warehouse:
        ins: []
        outs: []
        speed: 0
        materials:
            - wood
            - wood
            - stone
items:
    types:
        wood: {}
        stone: {}

